name: yaka2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cached_network_image: any
  material_floating_search_bar: ^0.3.7
  carousel_slider: ^4.0.0
  # dart_code_metrics: ^4.17.1
  flutter_iconly: ^1.0.2
  firebase_messaging: ^11.2.6
  firebase_core: any
  flutter_local_notifications: any
  flutter_staggered_grid_view: ^0.4.0
  http: any
  google_nav_bar: ^5.0.6
  restart_app: ^1.1.0
  vibration: ^1.7.5
  share: any
  pull_to_refresh: ^2.0.0
  lottie: ^1.2.1
  change_app_package_name: ^1.1.0
  get_storage: 2.0.3
  url_launcher: 6.1.6

  #usb
  # usb_serial: ^0.4.0
  # usb_device: ^0.0.7
  # quick_usb: ^0.4.0
  # flutter_usb_write: ^0.1.0
  # serial_communication: ^0.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  # flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
    - assets/image/banner/
    - assets/image/clothes/
    - assets/image/logo/
    - assets/image/machine/
    - assets/image/yaka/
    - assets/image/category/
  fonts: 
    - family: NormsProBold
      fonts: 
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: NormsProMedium
      fonts: 
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: NormsProRegular
      fonts: 
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: NormsProLight
      fonts: 
        - asset: assets/fonts/Montserrat-Regular.ttf
  uses-material-design: true
  generate: true

