name: yaka2
version: 1.0.5+5
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.3
  optimized_cached_image: ^3.0.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.0.0
  dio: null
  http: any
  cupertino_icons: ^1.0.2
  flutter_iconly: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  lottie: ^1.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.13.0
  pull_to_refresh: ^2.0.0
  restart_app: ^1.1.0
  share: any
  url_launcher: 6.1.6
  vibration: ^1.7.5
  open_file_manager: ^0.0.2
  firebase_core: any
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^8.2.0
  firebase_core_platform_interface: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
    - assets/image/instruction/
  fonts:
    - family: NormsProBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: NormsProMedium
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: NormsProRegular
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: NormsProLight
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true
