name: yaka2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cached_network_image: any
  carousel_slider: ^4.0.0
  flutter_iconly: ^1.0.2
  firebase_messaging: ^11.2.6
  firebase_core: any
  flutter_local_notifications: any
  flutter_staggered_grid_view: ^0.4.0
  http: any
  restart_app: ^1.1.0
  dio:
  vibration: ^1.7.5
  share: any
  pull_to_refresh: ^2.0.0
  lottie: ^1.2.1
  get_storage: 2.0.3
  url_launcher: 6.1.6
  flutter_downloader: ^1.7.4
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  # dart_code_metrics: ^4.17.1
  #usb
  # usb_serial: ^0.4.0
  # usb_device: ^0.0.7
  # quick_usb: ^0.4.0
  # flutter_usb_write: ^0.1.0
  # serial_communication: ^0.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  # flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
  fonts: 
    - family: NormsProBold
      fonts: 
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: NormsProMedium
      fonts: 
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: NormsProRegular
      fonts: 
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: NormsProLight
      fonts: 
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true

